# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "jekyll"
gem "webrick"
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem 'eventmachine', '~> 1.0.0'
group :jekyll_plugins do
    gem "jekyll-paginate-v2"
    gem "jekyll-feed"
  end